### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by ibesora** [geostarters/icgc-js-common#2]
As Node.js uses require/module.require and the library is written to use import/export when running tests, written using require syntax, an exception is thrown.

We should look at [this](https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953) article to see how to build a library that can be used for web and as ES6 modules at the same time

**Comment by geostarters** [comment]
Solved.
Currently using JEST for unit testing.

**Comment by jessisena** [comment]
Solved.
Currently using JEST for unit testing
